// js/data.js

let usuarioLogado = null;
let paginaAtual = 'login';
let voluntarios = [];

const VOLUNTARIOS_INICIAIS = [
    {
        id: 1,
        nome: "João Silva",
        telefone: "(51) 98765-4321",
        redeSocial: "@joaosilva",
        cep: "94940-000",
        rua: "Rua Marechal Floriano",
        numero: "200",
        complemento: "",
        bairro: "Centro",
        cidade: "Cachoeirinha",
        uf: "RS",
        escolaridade: "Superior",
        profissao: "",
        areaAtuacao: "Logística",
        tipo: "Sistemático",
        horarioDisponivel: "Fins de semana",
        publicoPreferencia: "Crianças",
        temExperiencia: true,
        localExperiencia: "Cruz Vermelha",
        hobby: "Futebol"
    },
    {
        id: 2,
        nome: "Maria Santos",
        telefone: "(51) 99876-5432",
        redeSocial: "@mariasantos",
        cep: "90010-170",
        rua: "Rua dos Andradas",
        numero: "1234",
        complemento: "Sala 3",
        bairro: "Centro Histórico",
        cidade: "Porto Alegre",
        uf: "RS",
        escolaridade: "Superior",
        profissao: "Dentista",
        areaAtuacao: "Saúde",
        tipo: "Sistemático",
        horarioDisponivel: "Terças e quintas",
        publicoPreferencia: "Idosos",
        temExperiencia: true,
        localExperiencia: "Hospital Beneficente",
        hobby: "Leitura"
    },
    {
        id: 3,
        nome: "Pedro Costa",
        telefone: "(51) 97654-3210",
        redeSocial: "@pedrocosta",
        cep: "94935-100",
        rua: "Av. Getúlio Vargas",
        numero: "890",
        complemento: "",
        bairro: "Parque Eldorado",
        cidade: "Cachoeirinha",
        uf: "RS",
        escolaridade: "Superior",
        profissao: "Arquiteto",
        areaAtuacao: "Construção",
        tipo: "Pontual",
        horarioDisponivel: "Eventos pontuais",
        publicoPreferencia: "Famílias",
        temExperiencia: false,
        localExperiencia: "",
        hobby: "Arquitetura"
    },
    {
        id: 4,
        nome: "Ana Paula",
        telefone: "(51) 96543-2109",
        redeSocial: "@anapaulapsico",
        cep: "90570-020",
        rua: "Av. Ipiranga",
        numero: "6681",
        complemento: "Bloco B Apto 204",
        bairro: "Partenon",
        cidade: "Porto Alegre",
        uf: "RS",
        escolaridade: "Superior",
        profissao: "Psicólogo",
        areaAtuacao: "Saúde Mental",
        tipo: "Sistemático",
        horarioDisponivel: "Fins de semana",
        publicoPreferencia: "Adolescentes",
        temExperiencia: true,
        localExperiencia: "Centro de Acolhimento",
        hobby: "Meditação"
    },
    {
        id: 5,
        nome: "Carlos Mendes",
        telefone: "(51) 95432-1098",
        redeSocial: "@carlosmendes",
        cep: "94940-420",
        rua: "Rua João Pessoa",
        numero: "350",
        complemento: "",
        bairro: "Jardim do Prado",
        cidade: "Cachoeirinha",
        uf: "RS",
        escolaridade: "Medio",
        profissao: "Eletricista",
        areaAtuacao: "Manutenção",
        tipo: "Pontual",
        horarioDisponivel: "Sábados",
        publicoPreferencia: "Comunidades",
        temExperiencia: true,
        localExperiencia: "Projeto Luz para Todos",
        hobby: "Eletrônica"
    }
];